version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - model_cache:/root/.cache/torch/sentence_transformers
    environment:
      - MONGODB_URI=mongodb+srv://giautoan:giautoan123@cluster0.mongodb.net/giautoan?retryWrites=true&w=majority
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - rag

  rag:
    build: ./Rag
    ports:
      - "8000:8000"
    volumes:
      - ./Rag:/app
      - model_cache:/root/.cache/torch/sentence_transformers
    environment:
      - MONGODB_URI=mongodb+srv://giautoan:giautoan123@cluster0.mongodb.net/giautoan?retryWrites=true&w=majority

volumes:
  model_cache:
    driver: local 