services:
  - type: web
    name: giasutoan-flask
    env: python
    buildCommand: pip install -r Backend/requirements.txt
    startCommand: cd Backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: ChatGiaSu
      - key: JWT_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_ENV
        value: production
      - key: CORS_ALLOWED_ORIGINS
        value: "*"

  - type: web
    name: giasutoan-fastapi
    env: python
    buildCommand: pip install -r Backend/requirements.txt
    startCommand: cd Backend && uvicorn API_Rag:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: ChatGiaSu
      - key: JWT_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: CORS_ALLOWED_ORIGINS
        value: "*"

  - type: web
    name: giasutoan-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s Frontend/dist -p $PORT
    envVars:
      - key: VITE_API_URL
        fromService:
          name: giasutoan-flask
          type: web
          property: url
      - key: VITE_RAG_API_URL
        fromService:
          name: giasutoan-fastapi
          type: web
          property: url 